# Generated by Django 5.0.3 on 2024-03-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_from',
            new_name='purchased_from',
        ),
    ]
